### ISSUE TITLE
Installation fails due to dependency

### ISSUE THREAD

**Issue by citronalco** [heartfin/harbour-sailfin#45]
OS: Sailfish 4.5.0.24
Arch: armv7hl

```
# rpm -i harbour-sailfin-0.5.0-1.armv7hl.rpm 
error: Failed dependencies:
        libQt5WebSockets.so.5(Qt_5) is needed by harbour-sailfin-0.5.0-1.armv7hl
```

But qt5-qtwebsockets-5 is installed:
```
# rpm -qa | grep qtwebs
qt5-qtwebsockets-5.7.0-10.24.1.jolla.armv7hl
```

Similar with zypper:
```
# zypper install harbour-sailfin
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: the to be installed harbour-sailfin-0.5.0-1.armv7hl requires 'libQt5WebSockets.so.5(Qt_5)', but this requirement cannot be provided
  not installable providers: qt5-qtwebsockets-5.5.1+git1-1.7.1.jolla.armv7hl[jolla]
 Solution 1: downgrade of qt5-qtwebsockets-5.7.0-10.24.1.jolla.armv7hl to qt5-qtwebsockets-5.5.1+git1-1.7.1.jolla.armv7hl
 Solution 2: do not install harbour-sailfin-0.5.0-1.armv7hl
 Solution 3: break harbour-sailfin-0.5.0-1.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c/d/?] (c):
```

**Comment by HenkKalkwater** [comment]
Huh, that is weird. I believe I only have set the dependency to [Qt5WebSockets](https://github.com/heartfin/harbour-sailfin/blob/c5541b0b16f56454027a4540386d0f3db9962c78/rpm/harbour-sailfin.yaml#L26) and I compiled it with the SailfishOS-4.5.0.18 target

**Comment by citronalco** [comment]
Strange enough, I got this:
```
[root@Sailfish usr]# ls -l /usr/lib/libQt5WebSockets*
lrwxrwxrwx    1 root     root            25 Dec 12  2015 /usr/lib/libQt5WebSockets.so.5 -> libQt5WebSockets.so.5.7.0
lrwxrwxrwx    1 root     root            25 Dec 12  2015 /usr/lib/libQt5WebSockets.so.5.7 -> libQt5WebSockets.so.5.7.0
-rwxr-xr-x    1 root     root        105980 Dec 12  2015 /usr/lib/libQt5WebSockets.so.5.7.0
```
So the requirement should be fulfilled. But I'm no expert in rpm.

`zypper in --from=jolla qt5-qtwebsockets` told me that `qt5-qtwebsockets-5.7.0-10.24.1.jolla.armv7hl`  was from another repo and recommended running `zypper install --oldpackage qt5-qtwebsockets-5.5.1+git1-1.7.1.jolla.armv7hl` to get back Jolla's version. What I did. After that I could install harbour-sailfin.

Maybe the newer qt5-qtwebsockets version I had was somehow badly packaged. No clue where it came from.

**Comment by HenkKalkwater** [comment]
I'm glad that worked for you. I'll be closing this issue then.

> No clue where it came from.

Have you perhaps enabled any custom repos, like OpenRepos or Chum that could have interfered? That'd be my guess.
